import type { Metadata } from "next";

import NavBar from "@/components/Shared/Header/NavBar";
import Footer from "@/components/Shared/Footer/page";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function WithLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NavBar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
